### PR TITLE
nlopt supporting C++ algorithms

### PR DESCRIPTION
**Pull request by druvus**
I would need a rebuild of the package to include the cxx flag during building. It is needed in phyx that I am trying to package for Bioconda.

### CODE REVIEW

**Comment by jschueller** [comment]
Really ? You know it's only one extra algorithm. Iby phyx ? Cannot find it.

**Comment by jschueller** [comment]
I'm not too happy about this, this will break several compiled binaries in conda-forge:
https://github.com/search?l=YAML&q=org%3Aconda-forge+nlopt&type=Code

**Comment by druvus** [comment]
@jschueller please see the cross-reference to the phyx repo. I am not too familiar with the nlopt code but I guess we need to confirm those changes are or are not breaking other packages.

**Comment by jschueller** [comment]
You dont need to enable cxx. For nlopt what it really does is enable the algorithm that is written in c++, but the api of nlopt remains C. The C++ interface for nlopt exists but is header-only and is not related to the with-cxx option. What you just have to do is tell phyx to link to nlopt instead of nlopt_cxx, here is the relevant phyx configure.ac line:
```
AC_SEARCH_LIBS([nlopt_urand], [nlopt_cxx], [have_nlopt=yes], [have_nlopt=no], [-lstdc++])
```
This phyx nlopt detection has to be improved, first look for nlopt, then nlopt_cxx+lstdc++.

**Comment by druvus** [comment]
thanks, I will try that.

**Pull request closed without merging**
