### PR TITLE
Build with pip

### PR DESCRIPTION
**Pull request by AntoineD**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

This PR builds `nlopt` with `pip` to prevent `nlopt `from being installed twice by `conda` and `pip`. This may happen when the installation of `nlopt` is triggered from different dependencies. Most conda python packages are built with `pip` to allow seamless integration of `conda` installed packages with `pip` installed packages.

In this PR, the build is done with `scikit-build` which should handle calling `cmake` and `ninja`.
This implies the following changes:
- the build scripts are longer necessary,
- the vendored cmake module `FindNumpy.cmake` is removed in order to use the native cmake one,
- `CMakeLists.txt` uses the native python discovery variables,
- a `setup.py` module is necessary for `pip`.

I was able to successfully test the built packages on linux, I cannot test on the other platforms. The conda-forge built will tell.

### CODE REVIEW

**Comment by jschueller** [comment]
-1
to avoid conflicts with pip you just need to add a METADATA file into a new dist-info dir in the python directory
no need to patch or use skbuild, this is overkill
you could send a PR to nlopt to add that file instead

**Comment by AntoineD** [comment]
True this is overkill, I'm actually also toying with scikit-build on the upstream pip packaging because some pypi versions are broken on windows.

I'll look at you proposal, thanks!

**Comment by jschueller** [comment]
the file should be installed like this: .../site-packages/nlopt-2.7.0.dist-info/METADATA

**Comment by AntoineD** [comment]
Should its content be the same as the one in the pypi package?

**Comment by jschueller** [comment]
I'm not sure if the content even matters, maybe it can even be empty.
But, yes it could be moved to that repo.

**Pull request closed without merging**
